version: '3.4'
services:

  #PHP Service
  app:
    image: learning-docker/laravel:v1
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=host.docker.internal  # Use host.docker.internal to connect to your local MySQL server
      - DB_PORT=3306
      - DB_DATABASE=english
      - DB_USERNAME=root
      - DB_PASSWORD=
    networks:
      - laravel-network
    
  #Nginx Service
  webserver:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network
      
networks:
  laravel-network: